/**
 * Matters / Exceptions engine (Implementation Guide §10) — the ONE reusable
 * mechanism serving Section 01 (Acceptance Matters) and Section 02 (Framework
 * Matters). Matters are GENERATED from adverse answers / overrides / pending
 * facts with a `source` back-link, never re-entered in a separate register
 * (guide principle #7). A blocking matter prevents section completion/approval.
 */

/** Which section a matter belongs to (drives the classification vocabulary). */
export const MATTER_SECTION = {
  acceptance: 'acceptance',
  framework: 'framework',
} as const;
export type MatterSection = (typeof MATTER_SECTION)[keyof typeof MATTER_SECTION];
export const MATTER_SECTIONS: MatterSection[] = Object.values(MATTER_SECTION);

/** Lifecycle of a matter. Terminal (closed) states are resolved / accepted. */
export const MATTER_STATUS = {
  open: 'open',
  underReview: 'under_review',
  resolved: 'resolved',
  acceptedWithApproval: 'accepted_with_approval',
  blocking: 'blocking',
} as const;
export type MatterStatus = (typeof MATTER_STATUS)[keyof typeof MATTER_STATUS];
export const MATTER_STATUSES: MatterStatus[] = Object.values(MATTER_STATUS);

/** Statuses that count as CLOSED (a closed blocking matter no longer gates). */
export const MATTER_CLOSED_STATUSES: MatterStatus[] = [
  MATTER_STATUS.resolved,
  MATTER_STATUS.acceptedWithApproval,
];

/** Severity for ACCEPTANCE matters (guide §8.4). */
export const MATTER_SEVERITY = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;
export type MatterSeverity = (typeof MATTER_SEVERITY)[keyof typeof MATTER_SEVERITY];
export const MATTER_SEVERITIES: MatterSeverity[] = Object.values(MATTER_SEVERITY);

/** Category for FRAMEWORK matters (guide §10). */
export const FRAMEWORK_MATTER_CATEGORY = {
  informationPending: 'information_pending',
  technicalJudgment: 'technical_judgment',
  frameworkOverride: 'framework_override',
  legalInterpretation: 'legal_interpretation',
  partnerConsultation: 'partner_consultation',
  blocking: 'blocking',
} as const;
export type FrameworkMatterCategory =
  (typeof FRAMEWORK_MATTER_CATEGORY)[keyof typeof FRAMEWORK_MATTER_CATEGORY];
export const FRAMEWORK_MATTER_CATEGORIES: FrameworkMatterCategory[] =
  Object.values(FRAMEWORK_MATTER_CATEGORY);

/** A single matter, as read by the compact Matters panel. */
export interface AuditMatterRecord {
  id: string;
  workflowInstanceId: string;
  engagementId: string;
  /** Human display code, e.g. `M-001`, stable per workflow instance. */
  matterCode: string;
  section: MatterSection;
  /** Back-link key to the originating question/segment/area (never a copy). */
  source: string;
  /** Optional row this matter was generated from (e.g. an assessment id). */
  sourceRef: string | null;
  /** One-line description of what triggered the matter. */
  title: string;
  /** Section-specific classification (FrameworkMatterCategory or acceptance category). */
  category: string;
  /** Acceptance severity, when applicable. */
  severity: string | null;
  /** True when open-and-unresolved this matter blocks section completion/approval. */
  isBlocking: boolean;
  /** True when auto-generated by the engine (vs. professionally raised). */
  isAuto: boolean;
  ownerName: string | null;
  dueDate: string | null;
  status: MatterStatus;
  resolution: string | null;
  approverName: string | null;
  approvedAt: string | null;
  /** Evidence link — points at a document row, never a duplicate copy (§16). */
  documentId: string | null;
  note: string | null;
  version: number;
  createdAt: string;
  updatedAt: string;
}

/** Update a matter (assign, transition status, resolve/accept). Optimistic-locked. */
export interface UpdateMatterInput {
  status?: MatterStatus;
  resolution?: string | null;
  ownerEmployeeId?: string | null;
  dueDate?: string | null;
  documentId?: string | null;
  note?: string | null;
  version: number;
}
